// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeD0q4LgybJNLBFtceA8cq6_8ImuwONCg',
    appId: '1:281185243336:web:f65ff7aef25a2ebf4455fd',
    messagingSenderId: '281185243336',
    projectId: 'qponerafire-5ad91',
    authDomain: 'qponerafire-5ad91.firebaseapp.com',
    storageBucket: 'qponerafire-5ad91.appspot.com',
    measurementId: 'G-DYV32MTWWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASGqgo9q2diNwwxF7hp8AGIwJC0lAKBg0',
    appId: '1:281185243336:android:303e588e22924c224455fd',
    messagingSenderId: '281185243336',
    projectId: 'qponerafire-5ad91',
    storageBucket: 'qponerafire-5ad91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAttgx6_72rY44IjRSugh-_Oge1XM-_AQI',
    appId: '1:281185243336:ios:cdca1ef5a8e677fd4455fd',
    messagingSenderId: '281185243336',
    projectId: 'qponerafire-5ad91',
    storageBucket: 'qponerafire-5ad91.appspot.com',
    iosBundleId: 'com.example.cuponeraFl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAttgx6_72rY44IjRSugh-_Oge1XM-_AQI',
    appId: '1:281185243336:ios:cdca1ef5a8e677fd4455fd',
    messagingSenderId: '281185243336',
    projectId: 'qponerafire-5ad91',
    storageBucket: 'qponerafire-5ad91.appspot.com',
    iosBundleId: 'com.example.cuponeraFl',
  );
}
