// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDODj3Vj2did1ZGC7wI0w505Uk6G9EvuA8',
    appId: '1:498775236147:web:7d47f90a1db6ae9353cd46',
    messagingSenderId: '498775236147',
    projectId: 'qponera-39e61',
    authDomain: 'qponera-39e61.firebaseapp.com',
    storageBucket: 'qponera-39e61.appspot.com',
    measurementId: 'G-6BEY86CCK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAwkyg149J-SIqN2L4Sgfp4ppklE9HADg',
    appId: '1:498775236147:android:5449a6d4ebf4b6e253cd46',
    messagingSenderId: '498775236147',
    projectId: 'qponera-39e61',
    storageBucket: 'qponera-39e61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2p_70gITSq6CTj5ndO7AwK6cPE4QJg8U',
    appId: '1:498775236147:ios:fbca72f2c2699e6553cd46',
    messagingSenderId: '498775236147',
    projectId: 'qponera-39e61',
    storageBucket: 'qponera-39e61.appspot.com',
    iosClientId: '498775236147-rl4aksqjhug97om24ecfvleag1atjod9.apps.googleusercontent.com',
    iosBundleId: 'com.example.cuponeraFl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2p_70gITSq6CTj5ndO7AwK6cPE4QJg8U',
    appId: '1:498775236147:ios:fbca72f2c2699e6553cd46',
    messagingSenderId: '498775236147',
    projectId: 'qponera-39e61',
    storageBucket: 'qponera-39e61.appspot.com',
    iosClientId: '498775236147-rl4aksqjhug97om24ecfvleag1atjod9.apps.googleusercontent.com',
    iosBundleId: 'com.example.cuponeraFl',
  );
}
